//
// Created by 48500 on 13.11.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_5_H
#define PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_5_H
int konstruktor_5();
#endif //PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_5_H
