//
// Created by 48500 on 13.11.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_3_H
#define PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_3_H
int konstruktor_3();
#endif //PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_3_H
