//
// Created by 48500 on 13.11.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_6_H
#define PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_6_H
int konstruktor_6();
#endif //PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_6_H
