//
// Created by 48500 on 05.12.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___DZIEDZICZENIE_1_H
#define PROGRAMOWANIEOBIEKTOWEC___DZIEDZICZENIE_1_H
int Dziedziczenie_1();
#endif //PROGRAMOWANIEOBIEKTOWEC___DZIEDZICZENIE_1_H
