//
// Created by 48500 on 05.12.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___DZIEDZICZENIE_2_H
#define PROGRAMOWANIEOBIEKTOWEC___DZIEDZICZENIE_2_H
int Dziedziczenie_2();
#endif //PROGRAMOWANIEOBIEKTOWEC___DZIEDZICZENIE_2_H
