//
// Created by 48500 on 13.11.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_4_H
#define PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_4_H
int konstruktor_4();
#endif //PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_4_H
