//
// Created by 48500 on 13.11.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_1_H
#define PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_1_H
int konstruktor_1();
#endif //PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_1_H
