//
// Created by 48500 on 13.11.2021.
//

#ifndef PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_2_H
#define PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_2_H
int konstruktor_2();
#endif //PROGRAMOWANIEOBIEKTOWEC___KONSTRUKTOR_2_H
